#!/usr/bin/env python3
"""Generate gzip-compressed HTML header from html_pages.h.

Reads html_pages.h, bakes shared CSS into each page, gzip compresses,
and outputs html_pages_gz.h with PROGMEM byte arrays.

Run automatically by build.sh before arduino-cli compile.
"""

import re
import gzip
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
INPUT = SCRIPT_DIR / "html_pages.h"
OUTPUT = SCRIPT_DIR / "html_pages_gz.h"

PAGE_NAMES = [
    "LOGIN_PAGE",
    "DASHBOARD_PAGE",
    "SETTINGS_PAGE",
    "TETRIS_PAGE",
    "UPDATE_PAGE",
]


def extract_pages(content: str) -> dict[str, str]:
    pages = {}
    for match in re.finditer(
        r'static const char (\w+)\[\] PROGMEM = R"rawliteral\((.*?)\)rawliteral"',
        content,
        re.DOTALL,
    ):
        pages[match.group(1)] = match.group(2)
    return pages


def to_c_array(data: bytes, indent: str = "    ") -> str:
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append(indent + ", ".join(f"0x{b:02x}" for b in chunk))
    return ",\n".join(lines)


def main():
    content = INPUT.read_text()
    pages = extract_pages(content)

    if "SHARED_CSS" not in pages:
        print("ERROR: SHARED_CSS not found in html_pages.h", file=sys.stderr)
        sys.exit(1)

    css = pages["SHARED_CSS"]

    out = []
    out.append("#ifndef HTML_PAGES_GZ_H")
    out.append("#define HTML_PAGES_GZ_H")
    out.append("")
    out.append("#include <Arduino.h>")
    out.append("")
    out.append("// Auto-generated — do not edit. Edit html_pages.h instead.")
    out.append("// Generated by compress_html.py (CSS pre-baked, gzip level 9)")
    out.append("")

    total_raw = 0
    total_gz = 0

    for name in PAGE_NAMES:
        if name not in pages:
            print(f"WARNING: {name} not found in html_pages.h", file=sys.stderr)
            continue

        baked = pages[name].replace("%CSS%", css)
        raw_bytes = baked.encode("utf-8")
        gz_data = gzip.compress(raw_bytes, compresslevel=9)

        total_raw += len(raw_bytes)
        total_gz += len(gz_data)

        var_name = f"{name}_GZ"
        out.append(f"static const uint8_t {var_name}[] PROGMEM = {{")
        out.append(to_c_array(gz_data))
        out.append("};")
        out.append(f"static const size_t {var_name}_LEN = sizeof({var_name});")
        out.append("")

    out.append("#endif // HTML_PAGES_GZ_H")
    out.append("")

    OUTPUT.write_text("\n".join(out))

    saving = total_raw - total_gz
    print(f"Compressed {len(PAGE_NAMES)} pages: {total_raw:,} -> {total_gz:,} bytes (saved {saving:,})")


if __name__ == "__main__":
    main()
